---
# this comment is a hack
version: '3'
services:
  handbrake:
    image: jlesage/handbrake@sha256:2a5a125d660f1d5a938a79e29082ee2a94c3f0d10e5e54d281c2829c572db1a2
    ports:
      - "5800:5800"
    volumes:
      - /docker/docker-compose/handbrake:/config:rw
      - /docker/docker-compose/handbrake/storage:/storage:ro
      - /docker/docker-compose/handbrake/watch:/watch:rw
      - /docker/docker-compose/handbrake/output:/output:rw
    restart: unless-stopped
    deploy:
      restart_policy:
        condition: on-failure
