---
# this comment is a also hack
version: '3'
services:
  handbrake:
    image: jlesage/handbrake@sha256:5f097b13a5d20efe829204deb8985a6c2b905af1b342a53365bc18e1dcbe465b
    ports:
      - "5800:5800"
    volumes:
      - /docker/docker-compose/handbrake:/config:rw
      - /docker/docker-compose/handbrake/storage:/storage:ro
      - /docker/docker-compose/handbrake/watch:/watch:rw
      - /docker/docker-compose/handbrake/output:/output:rw
    restart: unless-stopped
    deploy:
      restart_policy:
        condition: on-failure
